version: "3"

services:
  nginx-plus-s3-gateway:
    container_name: nginx-plus-s3-gateway
    build:
      context: ./
      dockerfile: ./Dockerfile.plus
    # If minio client is up and running properly, we are reasonably sure that
    # minio has properly started. That's why we depend on it here.
    image: "nginx-plus-s3-gateway"
    ports:
      - "80:80/tcp"
    restart: "no"
    environment:
      S3_BUCKET_NAME: "nginx-images"
      S3_ACCESS_KEY_ID: "ASIAZKS6SYCD7GKOLSEP"
      S3_SECRET_KEY: "gTl6Lj/tOFAhowgR4pwtlJhkZji9zPtoRIq3DJDz"
      S3_SERVER: s3.amazonaws.com
      S3_SERVER_PORT: 443
      S3_SERVER_PROTO: https
      S3_REGION: us-east-2
      S3_STYLE: virtual
      S3_DEBUG: true
      AWS_SIGS_VERSION: 2
      ALLOW_DIRECTORY_LIST: true
    # volumes:
    #   - type: bind
    #     source: ./common/etc/nginx
    #     target: /etc/nginx
    # volumes:
    #   - type: bind
    #     source: ./common/etc/nginx
    #     target: /etc/nginx
    #   - type: bind
    #     source: ./common/etc/nginx/include
    #     target: /etc/nginx/include
