version: "3"

networks: 
  mynetwork:
    name: mynetwork
    attachable: true

services:
  nginx-plus-minio-gateway:
    container_name: nginx-plus-minio-gateway
    build:
      context: ./
      dockerfile: ./Dockerfile.plus
    image: nginx-plus-minio-gateway
    ports:
      - "81:80/tcp"
    restart: "no"
    environment:
      S3_BUCKET_NAME: nginx-images
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_SESSION_TOKEN:
      S3_SERVER: minio
      S3_SERVER_PORT: 9099
      S3_SERVER_PROTO: http
      S3_REGION: us-east-1
      S3_STYLE: virtual
      S3_DEBUG: true
      AWS_SIGS_VERSION: 4
      ALLOW_DIRECTORY_LIST: true
    depends_on:
      - minio
    networks:
      - mynetwork

  nginx-plus-s3-gateway-01:
    container_name: nginx-plus-s3-gateway-01
    build:
      context: ./
      dockerfile: ./Dockerfile.plus
    image: "nginx-plus-s3-gateway-01"
    ports:
      - "82:80/tcp"
    restart: "no"
    environment:
      S3_BUCKET_NAME: "nginx-images-01"
      S3_ACCESS_KEY_ID: "AKIATLPXHA4NODUCIHS2"
      S3_SECRET_KEY: "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"
      S3_SESSION_TOKEN:
      S3_SERVER: s3-us-east-2.amazonaws.com
      S3_SERVER_PORT: 443
      S3_SERVER_PROTO: https
      S3_REGION: us-east-2
      S3_STYLE: virtual
      S3_DEBUG: true
      AWS_SIGS_VERSION: 4
      ALLOW_DIRECTORY_LIST: true

  nginx-plus-s3-gateway-02:
    container_name: nginx-plus-s3-gateway-02
    build:
      context: ./
      dockerfile: ./Dockerfile.plus
    image: "nginx-plus-s3-gateway-02"
    ports:
      - "83:80/tcp"
    restart: "no"
    environment:
      S3_BUCKET_NAME: "nginx-images"
      S3_ACCESS_KEY_ID: "ASIAZKS6SYCDYX4BFB65"
      S3_SECRET_KEY: "JHk9QT77By2S0v4sV4DFwohMGR4C+OLqC3Wfkfl6"
      S3_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEMv//////////wEaCXVzLWVhc3QtMSJHMEUCIQCWXkZ0LFjIADPXfyQf3zV5m0XCt2xLyOJU+HlodmjsDgIgN4DIpsF4qyL753NbgQOcGesQy+0LiSxLsVH9JtlBNnkqhAMIMxACGgw2NDEyMjIyMzAxNTEiDNdVggMCIVMfJ2T/1CrhAr0AAKam2kRC6VPI29v8nqumu/s7wTZ/e4b6JeEMdWfBCwj4icM37Mwip5G2PcIUcXPsGyPkkYlzcnpR0jIGcd+ozxwx+kN3dZBdAPKSXuw5vdBHo3aftIJ5+tMNtA0PLWDnPCp3hV5UA6u54nBI/l6Xu9XYV3sFV5P5VA4Cr4GmVJzL76Mnf+WXGlZm283dXCmEIcbtciFU1jWJYK67BdKMYqedXL8ov9/OCCy7s8qU6xNeGx7DPXi00CN2wBpTYXYBpU1S6ofBbWhW5vDi2epblvk4c1bVQtuFWO8lbqKdiI1KTNbWZhHl+k0RTMZGTX1AKaTrUcwF6z/FvpLQ7FJFMw79v7THCyRYLS6cfTRZu3ndqdBpWNWfYWrDBBQEQFu67VcaA66Ge7y8EUvJAiPKck0u4X0rQj5r35jBa8YC3f0nOCE2ciDY2PxP/y4fN5h5HtsjBfYnG93PaDgk4ru2MNPm/pAGOqYBNJtBz3Jp3mhpqqSFiaUeh4hQ26OxU/eTDa3WBnZIazeOM84alKcm0WWSPJQiU2yIQTn1YL3NTN59GeB6E4bQPpBxrXaWkVDZy/k7vmbf/Q+qIdFvfQ2D7hzJkC1WIYxmKgpcjwktLw/QyNTywVX/bpPuCwGAJNxdhozv2biaEtYrjAQMk4J3NIaulcgn4T8QPq6m20N9HawUjzL0+9dXylK+IaXJaw=="
      S3_SERVER: s3-us-east-2.amazonaws.com
      S3_SERVER_PORT: 443
      S3_SERVER_PROTO: https
      S3_REGION: us-east-2
      S3_STYLE: virtual
      S3_DEBUG: true
      AWS_SIGS_VERSION: 4
      ALLOW_DIRECTORY_LIST: true

    # volumes:
    #   - type: bind
    #     source: ./common/etc/nginx
    #     target: /etc/nginx
    # volumes:
    #   - type: bind
    #     source: ./common/etc/nginx
    #     target: /etc/nginx
    #   - type: bind
    #     source: ./common/etc/nginx/include
    #     target: /etc/nginx/include
    networks:
      - mynetwork

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9099:9099
    restart: "no"
    command: server --address :9099 --console-address :9000 /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION_NAME: us-east-1
      MINIO_DOMAIN: minio
      MINIO_BROWSER: on
    volumes:
      - type: bind
        source: ./storage/data
        target: /data
    networks:
      - mynetwork

  minio-client:
    container_name: minio-client
    depends_on:
      - "minio"
    image: "minio/mc"
    restart: "no"
    command: "admin trace --verbose nginx-test-gateway"
    environment:
      MC_HOST_nginx-test-gateway: "http://minioadmin:minioadmin@minio:9099"
    networks:
      - mynetwork
